#'
#' Return C++ code generated by \pkg{rstan}
#' 
#' @param object a \code{bdm} class object 
#' @param ... additional arguments to generic function
#' 
#' @export
getcpp <- function(object, ...) UseMethod("getcpp")
#'
#' @rdname getcpp
#' @export
getcpp.bdm <- function(object, ...) {
    
    if (length(object@model_cpp) == 0) {
        stanc_list_return <- stanc(model_code = object@model_code, model_name = object@model_name)
        cpp  <- stanc_list_return$cppcode
    } else {
        cpp <- object@model_cpp$model_cppcode
    }
    
    return(cpp)
}