#'
#' Return C++ code generated by \pkg{rstan}
#' 
#' @export
getcpp <- function(object, ...) UseMethod("getcpp")
#'
#' @rdname getcpp
#' @export
getcpp.bdm <- function(object) {
    
    if (length(object@model_cpp) == 0) {
        stanc_list_return <- stanc(model_code = object@model_code, model_name = object@model_name)
        cpp  <- stanc_list_return$cppcode
    } else {
        cpp <- object@model_cpp$model_cppcode
    }
    
    return(cpp)
}

#'
#' Return model parameters (including input data)
#' 
#' @export
getparams <- function(object, ...) UseMethod("getparams")
#'
#' @rdname getparams
#' @export
getparams.bdm <- function(object) {
    
    cpp <- getcpp(object)
    
    params <- grep("vals_r__ = context__.vals_r(", fixed = TRUE, value = TRUE, x = strsplit(cpp, "\n")[[1]])
    params <- sapply(strsplit(params, "\""), FUN = function(x) x[[2]])
    
    return(params)
}
