
#{{{ projection functions
setGeneric("project", function(.Object,harvest.project, ...) standardGeneric("project"))
#{{ project from bdm object under constant harvest or harvest rate specified as a single value across all iterations
setMethod("project",signature=c("bdm","vector"),function(.Object,harvest.project,time.project,harvest_rate = TRUE, ...) {
  
  # dimensions
  # **********
  n.time       <- .Object@data$T
  n.total.time <- n.time + time.project
  n.scenarios  <- length(harvest.project)
  n.iter       <- .Object@nsamples
  
  d.time <- as.numeric(.Object@data$year)
  d.time <- c(d.time,(d.time[n.time]+1):(d.time[n.time]+time.project))
  
  # harvest array
  # *************
  if(harvest_rate) {
    
    harvest <- array(0,dim=c(n.iter,n.total.time,n.scenarios))
    harvest[,1:n.time,] <- .Object@trace$harvest_rate
    
    # replicate iterations along first dimension
    harvest[,(n.time+1):n.total.time,] <- array(rep(as.vector(t(matrix(harvest.project,n.scenarios,time.project))),each=n.iter),dim=c(n.iter,time.project,n.scenarios))
    
  } else {
    
    harvest                           <- matrix(0,n.scenarios,n.total.time)
    harvest[,1:n.time]                <- matrix(.Object@data$harvest,n.scenarios,n.time,byrow=TRUE)
    harvest[,(n.time+1):n.total.time] <- matrix(harvest.project,n.scenarios,time.project)
    
    # replicate iterations along first dimension
    harvest <- array(rep(as.vector(t(harvest)),each=n.iter),dim=c(n.iter,n.total.time,n.scenarios))
  }
  
  # process error array
  # *******************
  ep <- array(0,dim=c(n.iter,n.total.time))
  ep[,1:n.time] <- .Object@trace$epsilon_p
  
  # process error sigma
  ep.sigma <- .Object@data$sigmaP
  
  # default process error correlation
  # Thorson (2014) CJFAS
  rho <- 0.43
  
  # initialise array with LN random value
  # generated by rstan
  ep[,n.time+1] <- rho * log(ep[,n.time]+ep.sigma^2/2) + sqrt(1-rho^2) * rnorm(n.iter,0,ep.sigma)
  
  # correlated random variates on log scale
  for(t in (n.time+2):n.total.time)
    ep[,t] <- rho * ep[,t-1] + sqrt(1-rho^2) * rnorm(n.iter,0,ep.sigma)
  
  # convert to natural scale
  ep[,(n.time+1):n.total.time] <- exp(ep[,(n.time+1):n.total.time]-ep.sigma^2/2)
  
  # depletion array
  # ***************
  x <- array(0,dim=c(n.iter,n.total.time,n.scenarios))
  x[,1:n.time,] <- .Object@trace$x
  
  for(s in 1:n.scenarios)
    for(t in (n.time+1):n.total.time)
      x[,t,s] <- .project_harvest(x[,t-1,s],ep[,t-1],harvest[,t-1,s],harvest_rate,.Object)
  
  # return
  # ******
  dimnames(x)       <- list(iter=1:n.iter,time=d.time,scenario=1:n.scenarios)
  dimnames(ep)      <- list(iter=1:n.iter,time=d.time)
  dimnames(harvest) <- list(iter=1:n.iter,time=d.time,scenario=1:n.scenarios)
  
  biomass <- apply(x,2:3,function(y) y * exp(.Object@trace$logK))
  dimnames(biomass) <- list(iter=1:n.iter,time=d.time,scenario=1:n.scenarios)
  
  if(harvest_rate) {
    list(run=.Object@run,scenarios=harvest.project,year=d.time,nsamples=n.iter,biomass=biomass,depletion=x,epsilon_p=ep,harvest=harvest*x,harvest_rate=harvest)
  } else {
    list(run=.Object@run,scenarios=harvest.project,year=d.time,nsamples=n.iter,biomass=biomass,depletion=x,epsilon_p=ep,harvest=harvest,harvest_rate=harvest/x)
  }
})
#{
.project_harvest <- function(x,ep,harvest,harvest_rate,.Object) {
  
  r    <- .Object@trace$r
  logK <- .Object@trace$logK
  dmsy <- .Object@trace$dmsy
  h    <- .Object@trace$h
  g    <- .Object@trace$g
  m    <- .Object@trace$m
  n    <- .Object@data$n
  
  if(harvest_rate) {
    pars <- data.frame(x=x,r=r,logK=logK,dmsy=dmsy,h=h,g=g,m=m,H=harvest*x,ep=ep)
  } else {
    pars <- data.frame(x=x,r=r,logK=logK,dmsy=dmsy,h=h,g=g,m=m,H=exp(log(harvest) - logK),ep=ep)
  }
  pars[,'H'] <- apply(pars,1,function(y) y['H'] <- min(y['H'],y['x']))
 
  x.out <- apply(pars,1,function(y) {
              if(y['x']<=y['dmsy']) { max((y['x'] + y['r'] * y['x'] * (1 - y['x']/y['h']) - y['H'])*y['ep'],0.01)
              } else max((y['x'] + y['g'] * y['m'] * y['x'] * (1 - y['x']^(n-1)) - y['H'])*y['ep'],0.01)
              })
    
  x.out
}
#}
#}}
#}}}


